### PR TITLE
chore(.github/pull_request_template.md): add a new pull request template

### LINKED ISSUE #3: Add more details in ".github/PULL_REQUEST_TEMPLATE.md"
## Enhancement

Need more details in ".github/PULL_REQUEST_TEMPLATE.md" about:
1. How to name a branch, commit and PR.
2. What is necessary in a good PR.

### PR DESCRIPTION
**Pull request by zong-zhe**
add a new pull request template

### What problem does this PR solve?

Issue Number: close #issue-3

Problem Summary: Need some more details in PR template to teach newcomers how to come up with a high quality PR.

### What is changed and how it works?
I learned some online posts and added some friendly details for the newcomers to the template.
### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [x] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features

### Release note

Please refer to [Release Notes Language Style Guide](https://kusionstack.io/docs/governance/release-policy/) to write a quality release note.

```release-note
None
```

### CODE REVIEW

**Review by Peefy — DISMISSED** [review]
LGTM

**Review by ldxdl — DISMISSED** [review]
lgtm

**Comment by zong-zhe** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by chai2010 — APPROVED** [review]
LGTM

**Review by Peefy — APPROVED** [review]
lGTM

**Pull request merged**
